on: 
  push:
    branches: [master]
    
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: generate docs
        run: |
          gem install yard
          yard
      - name: push docs
        run: |
          git fetch --depth=1 origin gh-pages
          git checkout gh-pages
          rm -rf docs
          mv doc docs
          git config --local user.email "docs-action@github.com"
          git config --local user.name "GitHub Action (docs)"
          git add docs
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m 'Add docs'
          git push origin gh-pages
